// <auto-generated />
using System;
using LibraryManagement.Persistence.Postgres.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LibraryManagement.Persistence.Postgres.Migrations.Migrations
{
    [DbContext(typeof(LibraryManagementDbContext))]
    [Migration("20251204161305_AddAiConsumptionEntity")]
    partial class AddAiConsumptionEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LibraryManagement.Persistence.Postgres.DbContexts.Multitenants.Domains.Tenants.TenantEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tenants", (string)null);
                });

            modelBuilder.Entity("LibraryManagement.Persistence.Postgres.Domains.Ai.AiConsumption.AiConsumptionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("InputTokens")
                        .HasColumnType("bigint");

                    b.Property<string>("ModelUsed")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long>("OutputTokens")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<long>("TotalTokens")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("AiConsumptions", (string)null);
                });

            modelBuilder.Entity("LibraryManagement.Persistence.Postgres.Domains.Authors.AuthorEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Authors", (string)null);
                });

            modelBuilder.Entity("LibraryManagement.Persistence.Postgres.Domains.Books.BookEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("TenantId");

                    b.ToTable("Books", (string)null);
                });

            modelBuilder.Entity("LibraryManagement.Persistence.Postgres.Domains.Books.BookKeywordEntity", b =>
                {
                    b.Property<Guid>("BookId")
                        .HasColumnType("uuid");

                    b.Property<string>("Keyword")
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("BookId", "Keyword");

                    b.HasIndex("TenantId");

                    b.ToTable("BookKeyword", (string)null);
                });

            modelBuilder.Entity("LibraryManagement.Persistence.Postgres.Domains.Ai.AiConsumption.AiConsumptionEntity", b =>
                {
                    b.HasOne("LibraryManagement.Persistence.Postgres.DbContexts.Multitenants.Domains.Tenants.TenantEntity", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("LibraryManagement.Persistence.Postgres.Domains.Authors.AuthorEntity", b =>
                {
                    b.HasOne("LibraryManagement.Persistence.Postgres.DbContexts.Multitenants.Domains.Tenants.TenantEntity", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("LibraryManagement.Persistence.Postgres.Domains.Books.BookEntity", b =>
                {
                    b.HasOne("LibraryManagement.Persistence.Postgres.Domains.Authors.AuthorEntity", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LibraryManagement.Persistence.Postgres.DbContexts.Multitenants.Domains.Tenants.TenantEntity", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("LibraryManagement.Persistence.Postgres.Domains.Books.BookKeywordEntity", b =>
                {
                    b.HasOne("LibraryManagement.Persistence.Postgres.Domains.Books.BookEntity", "Book")
                        .WithMany("Keywords")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryManagement.Persistence.Postgres.DbContexts.Multitenants.Domains.Tenants.TenantEntity", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("LibraryManagement.Persistence.Postgres.Domains.Authors.AuthorEntity", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("LibraryManagement.Persistence.Postgres.Domains.Books.BookEntity", b =>
                {
                    b.Navigation("Keywords");
                });
#pragma warning restore 612, 618
        }
    }
}
